# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
        - node/install
        - checkout
        - run:
            name: Stuff to do
            command: |
              echo "Test could be done here"

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Set EB environment
          command: |
            npm run backend:start-init
      - run:
          name: Set EB environment variables
          command: |
            npm run backend:set-env
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy API
          command: |
            npm run backend:deploy
workflows:
  udagram-flow:
    jobs:
      - build
      - deploy:
          requires:
           - build
